Repository bf2fc6cc711aee1a0c2a/architecture, pull requests merged in 2022-06, with the labels that each got.

#27 feat: AP-2 Blast radius reduction principle
  _ap/2/index.adoc
Labels: state: needs-reviewers, notice: overdue

#22 feat: AP-7 Update / upgrade responsibility principle
  _ap/7/index.adoc
Labels: state: needs-reviewers, notice: overdue

#59 Add ADR-79 in Accepted state
  _adr/79/index.asciidoc
Labels: state: needs-reviewers

#28 feat: AP-12 How to push rules from git to production
  _ap/12/index.adoc
Labels: state: needs-reviewers, notice: overdue

#67 Add the contents for ADR 86 - Canary authentication with sso.redhat.com
  _adr/86/adr-86-current-authentication-flow.png
  _adr/86/adr-86-proposed-authentication-flow.png
  _adr/86/index.adoc
Labels: notice: overdue
